### ISSUE TITLE
Items ordering

### ISSUE THREAD

**Issue by chikamichi** [UJKhokhar/blocitoff#6]
Hi,

When I add an item to the list, it's prepended to the list, but if I refresh, the items are ordered by creation date, DESC. A default scope could fix that.

**Comment by UJKhokhar** [comment]
Thanks for pointing this out. Issue addressed here: https://github.com/UJKhokhar/blocitoff/commit/fd3655fc3bc2270c6839e8f08c85ef7a4d367d0e
