### ISSUE TITLE
What about some styling and better wordings?

### ISSUE THREAD

**Issue by chikamichi** [UJKhokhar/blocitoff#7]
Hi,

It's all functional and everything, but not very pretty :) Would you add some styles, using Bootstrap? Maybe some better wordings, too.

For instance:

* the items list could be styled using ["list group"](http://getbootstrap.com/components/#list-group)
* the text input could be styled using ["form"](http://getbootstrap.com/css/#forms)
* the text input's label could be more engaging, for instance "Add a new item"
* an area along the list, explaining what will happen to items older than 7 days, would be very valuable

Feel free to add some more styles and to personalize the app's look & feel (UI, nav bar, flash messages…)

**Comment by chikamichi** [comment]
Don't forget this is an application you may want to show to future employers during interviews (live on Heroku and/or as a code base): demonstrating a good attention to details is highly valuable :)

**Comment by UJKhokhar** [comment]
Styles updated have been updated here https://github.com/UJKhokhar/blocitoff/commit/d6187112afd3f0e0c8609eaee974fbf48d353001 and here https://github.com/UJKhokhar/blocitoff/commit/37a93151aa469455b4996a1a080318cb554087f6 :+1:
