### ISSUE TITLE
Default route

### ISSUE THREAD

**Issue by chikamichi** [UJKhokhar/blocitoff#8]
Hi,

When I sign in, I'm redirected to my user page, where I can see my list. I think it could be nice to set the root page to the user's personnal page, so that simply browsing http://localhost:3000/ displays the to-do list.

**Comment by chikamichi** [comment]
Also, when I'm logged out, the current root page (welcome#index) says

```
Welcome#index
Find me in app/views/welcome/index.html.erb
```

which is not very professional :) A welcome message, with a link to the sign-up and sign-in forms, could greatly enhance the UX.

**Comment by UJKhokhar** [comment]
Done and done! 

User root was changed here: 4c31b45 and welcome#index was updated here: 2d48db5
